### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by zx8754** [smgogarten/PlateMap#1]
Do you mind adding some examples of usage?

I have been thinking of creating similar package, never got a chance to do it. If I could test your package with examples, maybe we could collaborate and improve the package?

**Comment by smgogarten** [comment]
I have been meaning to write a vignette with more examples, but I haven't gotten to it yet. There is a small example in the man page, but I agree more are called for. I would welcome the collaboration, thanks!

**Comment by smgogarten** [comment]
Added a vignette.
